evaluation: 'ancilla'

# Paths to store result outputs in
paths:
  image: 'final_eval_folder/plots/'
  json: '' 

# Parameters for Generating Circuits
num_q: 12
num_g: 60
num_a_min: 5
num_a_max: 15
num_a_step: 1

# Parameters for running evaluations
num_circuits: 10

# Distance Metric ['euclidean', 'manhattan', 'wasserstein', 'jensenshannon']
distance: 'wasserstein'
num: 3