# Paths to store result outputs in
evaluation: 'ancilla'

paths:
  image: 'final_eval_folder/plots/'
  json: '' 

# Parameters for Generating Circuits
num_q: 10
num_g: 50
num_a_min: 3
num_a_max: 10
num_a_step: 1

# Parameters for running evaluations
num_circuits: 10

# Distance Metric ['euclidean', 'manhattan', 'wasserstein', 'jensenshannon']
distance: 'manhattan'
num: 0